# system
mode: 0
distribute: True
enable_graph_kernel: False
num_parallel_workers: 4
val_while_train: True
val_interval: 10
save_best: True
save_last: True

# dataset
dataset_format: "coco_topdown"
train_root: "data/coco/images/train2017"
train_label: "data/coco/annotations/person_keypoints_train2017.json"
val_root: "data/coco/images/val2017"
val_label: "data/coco/annotations/person_keypoints_val2017.json"
val_detection_result: "data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json"
val_use_gt_bbox: True
batch_size: 128
num_joints: 17
dataset_setting:
  image_size: [192, 256]
  heatmap_size: [48, 64]
  pixel_std: 200.
  scale_padding: 1.25
  det_bbox_thr: 0.
  flip_pairs:
    [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]]
  upper_body_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# pipeline
pipeline_method: "topdown"
normalize_mean: [0.485, 0.456, 0.406]
normalize_std: [0.229, 0.224, 0.255]
train_transforms:
  - topdown_box_to_center_scale
  - topdown_horizontal_random_flip:
      flip_prob: 0.5
  - topdown_halfbody_transform:
      prob_half_body: 0.3
      scale_padding: 1.5
  - topdown_randomscale_rotation:
      rot_factor: 40
      scale_factor: 0.5
      rot_prob: 0.6
  - topdown_affine:
      use_udp: True
  - topdown_generate_target:
      sigma: 2.
      use_udp: True
val_transforms:
  - topdown_box_to_center_scale
  - topdown_affine:
      use_udp: True

# model
in_channels: 3
backbone_name: "hrnet_w48"
backbone_setting: {}
backbone_pretrained: True
backbone_ckpt_url: "https://download.mindspore.cn/toolkits/mindcv/hrnet/hrnet_w48-2e3399cd.ckpt"
neck_name: ""
neck_out_channels: null
neck_setting: {}
head_name: "hrnet_head"
head_setting: {}
decoder_name: "topdown_heatmap"
decoder_setting:
  use_udp: True
  dark_udp_refine: False
  kernel_size: 11

# loss
loss: "joint_mse"
loss_with_extra_input: True
loss_setting:
  use_target_weight: True

# mix-precision training
amp_level: "O2"

# lr scheduler
scheduler: "warmup_multi_step_decay"
num_epochs: 210
lr: 0.001
warmup: 500
lr_scheduler_setting:
  milestones: [170, 200]

# optimizer
optimizer: "adamw"
weight_decay: 0.05
filter_bias_and_bn: True
optimizer_setting: {}

# evaluation
inference_method: "topdown_heatmap"
eval_method: "topdown"
eval_metric: ["AP"]
eval_setting:
  has_heatmap_output: True
  hflip_tta: False
  shift_heatmap: False
  vis_thr: 0.2
  oks_thr: 0.9
  use_nms: True
  soft_nms: False
  sigmas:
    [
      0.026,
      0.025,
      0.025,
      0.035,
      0.035,
      0.079,
      0.079,
      0.072,
      0.072,
      0.062,
      0.062,
      0.107,
      0.107,
      0.087,
      0.087,
      0.089,
      0.089,
    ]
