# system
mode: 0
distribute: True
enable_graph_kernel: False
num_parallel_workers: 4
val_while_train: True
val_interval: 10
save_best: True
save_last: True

# dataset
dataset_format: "coco_bottomup"
train_root: "data/coco/images/train2017"
train_label: "data/coco/annotations/person_keypoints_train2017.json"
val_root: "data/coco/images/val2017"
val_label: "data/coco/annotations/person_keypoints_val2017.json"
val_detection_result: null
val_use_gt_bbox: null
batch_size: 32
num_joints: 17
dataset_setting:
  image_size: [512, 512]
  max_image_size: [832, 512]
  heatmap_sizes: [[128, 128], [256, 256]]
  sigma: 2.
  expand_mask: True
  pixel_std: 200.
  tag_per_joint: True
  flip_pairs:
    [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]]

# pipeline
pipeline_method: "bottomup"
normalize_mean: [0.485, 0.456, 0.406]
normalize_std: [0.229, 0.224, 0.225]
train_transforms:
  - bottomup_random_affine:
      rot_factor: 30
      scale_factor: [0.75, 1.5]
      scale_type: "short"
      trans_factor: 40
  - bottomup_horizontal_random_flip:
      flip_prob: 0.5
  - bottomup_generate_target:
      sigma: 2.
      max_num: 30
val_transforms:
  - bottomup_rescale
  - bottomup_pad

# model
in_channels: 3
backbone_name: "hrnet_w32"
backbone_setting: {}
backbone_pretrained: True
backbone_ckpt_url: "https://download.mindspore.cn/toolkits/mindcv/hrnet/hrnet_w32-cc4fbd91.ckpt"
neck_name: ""
neck_out_channels: null
neck_setting: {}
head_name: "higher_hrnet_head"
head_setting:
  with_ae_loss: [True, False]
  tag_per_joint: True
decoder_name: "bottomup_heatmap_ae"
decoder_setting:
  with_ae_loss: [True, False]
  tag_per_joint: True
  num_joints: 17
  num_stages: 2
  use_nms: True
  nms_kernel: 3
  max_num: 30
  shift_coordinate: False

# loss
loss: "ae_multi_loss"
loss_with_extra_input: True
loss_setting:
  num_joints: 17
  num_stages: 2
  stage_sizes: [[128, 128], [256, 256]]
  mse_loss_factor: [1.0, 1.0]
  ae_loss_factor: [0.001, 0.001]
  with_mse_loss: [True, True]
  with_ae_loss: [True, False]
  tag_per_joint: True

# mix-precision training
amp_level: "O2"

# lr scheduler
scheduler: "warmup_cosine_decay"
num_epochs: 300
lr: 0.0005
warmup: 500
lr_scheduler_setting: {}

# optimizer
optimizer: "adam"
weight_decay: 0.
filter_bias_and_bn: True
optimizer_setting: {}

# evaluation
inference_method: "bottomup_heatmap_ae"
eval_method: "bottomup"
eval_metric: ["AP"]
eval_setting:
  has_heatmap_output: True
  hflip_tta: False
  downsample_scale: 2
  vis_thr: 0.1
  oks_thr: 0.9
  tag_thr: 1.0
  joint_order: [0, 1, 2, 3, 4, 5, 6, 11, 12, 7, 8, 9, 10, 13, 14, 15, 16]
  ignore_too_much: False
  use_rounded_norm: True
  use_nms: False
  soft_nms: False
  refine_missing_joint: False
  sigmas:
    [
      0.026,
      0.025,
      0.025,
      0.035,
      0.035,
      0.079,
      0.079,
      0.072,
      0.072,
      0.062,
      0.062,
      0.107,
      0.107,
      0.087,
      0.087,
      0.089,
      0.089,
    ]
